### ISSUE TITLE
What bin directory?

### ISSUE THREAD

**Issue by tedstrauss** [cameronhunter/glacier-cli#4]
> Download a release, extract the files and add the bin directory to your PATH.

What bin directory?

**Comment by cameronhunter** [comment]
Following the instructions in the [Getting Started](https://github.com/cameronhunter/glacier-cli#getting-started) section of the wiki:

> Download a [release](https://github.com/cameronhunter/glacier-cli/downloads), extract the files and add the `bin` directory to your `PATH`.

When extracted, the release package will look like:

![screen shot 2017-07-01 at 15 02 05](https://user-images.githubusercontent.com/246534/27765731-938f8f9c-5e6e-11e7-9716-acdddd198a25.png)

Add the `bin` directory to your `PATH`.
