### ISSUE TITLE
How am I supposed to run this?

### ISSUE THREAD

**Issue by Zamana** [cameronhunter/glacier-cli#5]
Hi!

After downloading and extracting, I can't see any binaries or bytecodes or whatever that is runnable. And no compiling instructions either.

How do I run this command?

Thanks.
Regards.

**Comment by cameronhunter** [comment]
Currently you need to build it yourself using `mvn package`. I haven't figured out a deployment strategy since GitHub deprecated the Downloads API. I'm open to suggestions if you have any, perhaps a CLI npm package?

**Comment by Zamana** [comment]
Ok. Thanks for quick reply.

Well... I have no idea. But where are those "mvn package" instructions?

Thanks.
Regards.
